config/routes.rb
Rails.application.routes.draw do
  resources :ecom_orders
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"



  root 'ecom_orders#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ecom_order.rb
class EcomOrder < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ecom_orders_controller.rb
class EcomOrdersController < ApplicationController
  before_action :set_ecom_order, only: %i[ show edit update destroy ]

  # GET /ecom_orders or /ecom_orders.json
  def index
    @ecom_orders = EcomOrder.all
  end

  # GET /ecom_orders/1 or /ecom_orders/1.json
  def show
  end

  # GET /ecom_orders/new
  def new
    @ecom_order = EcomOrder.new
  end

  # GET /ecom_orders/1/edit
  def edit
  end

  # POST /ecom_orders or /ecom_orders.json
  def create
    @ecom_order = EcomOrder.new(ecom_order_params)

    respond_to do |format|
      if @ecom_order.save
        format.html { redirect_to ecom_order_url(@ecom_order), notice: "Ecom order was successfully created." }
        format.json { render :show, status: :created, location: @ecom_order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ecom_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ecom_orders/1 or /ecom_orders/1.json
  def update
    respond_to do |format|
      if @ecom_order.update(ecom_order_params)
        format.html { redirect_to ecom_order_url(@ecom_order), notice: "Ecom order was successfully updated." }
        format.json { render :show, status: :ok, location: @ecom_order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ecom_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ecom_orders/1 or /ecom_orders/1.json
  def destroy
    @ecom_order.destroy

    respond_to do |format|
      format.html { redirect_to ecom_orders_url, notice: "Ecom order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ecom_order
      @ecom_order = EcomOrder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ecom_order_params
      params.require(:ecom_order).permit(:price, :itek_sku, :purchase_date, :platform_order_num, :sales_channel, :status, :customer_name, :customer_state, :shipped_at, :num_items_shipped, :payment_method)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ecom_orders_helper.rb
module EcomOrdersHelper
end

app/views/ecom_orders/_ecom_order.html.erb
<div id="<%= dom_id ecom_order %>">
  <p>
    <strong>Price:</strong>
    <%= ecom_order.price %>
  </p>

  <p>
    <strong>Itek sku:</strong>
    <%= ecom_order.itek_sku %>
  </p>

  <p>
    <strong>Purchase date:</strong>
    <%= ecom_order.purchase_date %>
  </p>

  <p>
    <strong>Platform order num:</strong>
    <%= ecom_order.platform_order_num %>
  </p>

  <p>
    <strong>Sales channel:</strong>
    <%= ecom_order.sales_channel %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= ecom_order.status %>
  </p>

  <p>
    <strong>Customer name:</strong>
    <%= ecom_order.customer_name %>
  </p>

  <p>
    <strong>Customer state:</strong>
    <%= ecom_order.customer_state %>
  </p>

  <p>
    <strong>Shipped at:</strong>
    <%= ecom_order.shipped_at %>
  </p>

  <p>
    <strong>Num items shipped:</strong>
    <%= ecom_order.num_items_shipped %>
  </p>

  <p>
    <strong>Payment method:</strong>
    <%= ecom_order.payment_method %>
  </p>

</div>

app/views/ecom_orders/_form.html.erb
<%= form_with(model: ecom_order) do |form| %>
  <% if ecom_order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ecom_order.errors.count, "error") %> prohibited this ecom_order from being saved:</h2>

      <ul>
        <% ecom_order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :itek_sku, style: "display: block" %>
    <%= form.text_field :itek_sku %>
  </div>

  <div>
    <%= form.label :purchase_date, style: "display: block" %>
    <%= form.datetime_field :purchase_date %>
  </div>

  <div>
    <%= form.label :platform_order_num, style: "display: block" %>
    <%= form.text_field :platform_order_num %>
  </div>

  <div>
    <%= form.label :sales_channel, style: "display: block" %>
    <%= form.text_field :sales_channel %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :customer_name, style: "display: block" %>
    <%= form.text_field :customer_name %>
  </div>

  <div>
    <%= form.label :customer_state, style: "display: block" %>
    <%= form.text_field :customer_state %>
  </div>

  <div>
    <%= form.label :shipped_at, style: "display: block" %>
    <%= form.datetime_field :shipped_at %>
  </div>

  <div>
    <%= form.label :num_items_shipped, style: "display: block" %>
    <%= form.number_field :num_items_shipped %>
  </div>

  <div>
    <%= form.label :payment_method, style: "display: block" %>
    <%= form.text_field :payment_method %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ecom_orders/edit.html.erb
<h1>Editing ecom order</h1>

<%= render "form", ecom_order: @ecom_order %>

<br>

<div>
  <%= link_to "Show this ecom order", @ecom_order %> |
  <%= link_to "Back to ecom orders", ecom_orders_path %>
</div>

app/views/ecom_orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Ecom orders</h1>

<%= link_to "New ecom order", new_ecom_order_path %>


    <table class="display table table-bordered table-responsive" id="data">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">price</th>
            <th scope="col">itek_sku</th>
            <th scope="col">purchase_date</th>
            <th scope="col">platform_order_num</th>
            <th scope="col">sales_channel</th>
            <th scope="col">status</th>
            <th scope="col">customer_name</th>
            <th scope="col">customer_state</th>
            <th scope="col">shipped_at</th>
            <th scope="col">num_items_shipped</th>
            <th scope="col">payment_method</th>
          </tr>
        </thead>
        <tbody>
          <% @ecom_orders.each do |f| %>
          <tr>
            <th><%=f.id%></th>
            <td><%=f.price%></td>
            <td><%=f.itek_sku %></td>
            <td><%=f.purchase_date%></td>
            <td><%=f.platform_order_num%></td>
            <td><%=f.sales_channel%></td>
            <td><%=f.status%></td>
            <td><%=f.customer_name%></td>
            <td><%=f.customer_state%></td>
            <td><%=f.shipped_at%></td>
            <td><%=f.num_items_shipped%></td>
            <td><%=f.payment_method%></td>
          </tr>
          <% end %>
        </tbody>
    </table>
</div>

<script>
$(document).ready(function () {
   $('#data').dataTable();
});
</script>
 

app/views/ecom_orders/new.html.erb
<h1>New ecom order</h1>

<%= render "form", ecom_order: @ecom_order %>

<br>

<div>
  <%= link_to "Back to ecom orders", ecom_orders_path %>
</div>

app/views/ecom_orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ecom_order %>

<div>
  <%= link_to "Edit this ecom order", edit_ecom_order_path(@ecom_order) %> |
  <%= link_to "Back to ecom orders", ecom_orders_path %>

  <%= button_to "Destroy this ecom order", @ecom_order, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Datatable</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>

    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
  </head>
  <body>
    <%= yield %>
  </body>
</html>